from __future__ import annotations


REGIME_COLUMNS = [
    "DE Wind Power Production MWh/h 15min Forecast__mean",
    "DE Solar Photovoltaic Production MWh/h 15min Forecast__mean",
    "DE Residual Load MWh/h 15min Forecast__mean",
    "DE Consumption Temperature °C 15min Forecast__mean",
    "DE Consumption MWh/h 15min Forecast__mean",
    "hour_sin",
    "hour_cos",
    "dow_sin",
    "dow_cos",
    "woy_sin",
    "woy_cos",
    "month_sin",
    "month_cos",
    "is_holiday_de",
    "is_weekend",
]


REGIME_COLUMNS_PCA = [
    "DE Wind Power Production MWh/h 15min Forecast__mean",
    "DE Solar Photovoltaic Production MWh/h 15min Forecast__mean",
    "DE Residual Load MWh/h 15min Forecast__mean",
    "DE Consumption Temperature °C 15min Forecast__mean",
    "DE Consumption MWh/h 15min Forecast__mean",
    "hour_sin",
    "hour_cos",
    "dow_sin",
    "dow_cos",
    "woy_sin",
    "woy_cos",
    "month_sin",
    "month_cos",
    "is_holiday_de",
    "is_weekend",
    "AT Residual Load MWh/h 15min Forecast__mean",
    "BE Residual Load MWh/h 15min Forecast__mean",
    "CH Residual Load MWh/h 15min Forecast__mean",
    "CZ Residual Load MWh/h 15min Forecast__mean",
    "DK Residual Load MWh/h 15min Forecast__mean",
    "FR Residual Load MWh/h 15min Forecast__mean",
    "NL Residual Load MWh/h 15min Forecast__mean",
    "PL Residual Load MWh/h 15min Forecast__mean",
    "AT Consumption Temperature °C 15min Forecast__mean",
    "BE Consumption Temperature °C 15min Forecast__mean",
    "CH Consumption Temperature °C 15min Forecast__mean",
    "CZ Consumption Temperature °C 15min Forecast__mean",
    "DK Consumption Temperature °C 15min Forecast__mean",
    "FR Consumption Temperature °C 15min Forecast__mean",
    "NL Consumption Temperature °C 15min Forecast__mean",
    "PL Consumption Temperature °C 15min Forecast__mean",
    "NL Futures Natural Gas EUR/MWh ICE-TTF OHLC",
    "Futures EUA EUR/t ICE OHLC",
    "Futures Coal API-2 USD/t ICE OHLC",
    "Futures Gasoil USD/t ICE OHLC",
    "Futures Crude Oil Brent USD/bbl ICE OHLC",
]
